make:
	cd h3-3.6.0; cmake . -DBUILD_SHARED_LIBS=true -DBUILD_FILTERS=OFF -DBUILD_BENCHMARKS=OFF; make
install:
	: # do nothing, we'll load the lib directly
clean:
	: # do nothing, cleanup happens when shard uninstalled