name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal:0.31.1
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install cmake make gcc libtool -y
        make -C ext
        shards install
    - name: Linting
      run: |
        crystal tool format --check
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=`cd ext/h3/lib && pwd`:$LD_LIBRARY_PATH
        crystal spec
