name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.14.0

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install cmake make gcc libtool -y
    - name: Check cmake version
      run: cmake --version
    - name: Build H3 C library
      run: make -C ext
    - name: Install shards
      run: shards install
    - name: Linting
      run: |
        crystal tool format --check
    - name: Run tests
      run: |
        crystal spec --verbose
