name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal:1.7.2
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: uber/h3
        ref: v3.6.0
        path: h3-3.6.0
    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install cmake make gcc libtool -y
        cd h3-3.6.0; cmake .; make install
        cd ..; shards install
    - name: Linting
      run: |
        crystal tool format --check
    - name: Run tests
      run: |
        crystal spec --verbose
