name: Crystal CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal:latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec

